### ISSUE TITLE
[   script:sonorancms] SCRIPT ERROR: @sonorancms/server/pushEvents.lua:1218: attempt to index a nil value (field 'charinfo')

### ISSUE THREAD

**Issue by subhampro** [Sonoran-Software/sonorancms_core#20]
![image](https://github.com/Sonoran-Software/sonorancms_core/assets/33375250/91dd9257-adff-4c09-9285-f8b36c611feb)

**Comment by nathanctech** [comment]
Please provide your QB-Core version and an example record from your "players" table.
