### ISSUE TITLE
Unauthorized: You do not have permission to view this page! When we click on QbCore Game Panel

### ISSUE THREAD

**Issue by subhampro** [Sonoran-Software/sonorancms_core#31]
![image](https://github.com/Sonoran-Software/sonorancms_core/assets/33375250/c752359a-1afd-4a6a-b7f4-294e5836673c)

**Comment by SonoranBrian** [comment]
This is because you do not have any servers added in the CMS API panel.
This is tracked as a known bug in our Discord.
Admin > Integrations > Sonoran CMS API > Servers > Add
